### PR TITLE
add a `repeat_n` algorithm; fix gcc TSAN errors

### LINKED ISSUE #725: Implement a `repeat[_n]` algorithm
See discussion and possible design at brycelelbach/wg21_p2300_execution#4

### PR DESCRIPTION
**Pull request by ericniebler**
fixes #725

### CODE REVIEW

File: test/exec/test_repeat_n_fail.cpp [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+ */
+
+#include <stdexec/execution.hpp>
+#include <exec/repeat_n.hpp>
+
+namespace ex = stdexec;
+
+int main() {
+  ex::sender auto snd = ex::just(42) | exec::repeat_n(10);
+  // build error: _INVALID_ARGUMENT_TO_REPEAT_N_
```
Comment (maikel) [inline test/exec/test_repeat_n_fail.cpp:25]: Great test!
