### PR TITLE
Fix thread safety bug in split sender notify

### LINKED ISSUE #1354: TSAN failure in `split`
I periodically see the "`split` is thread-safe" test fail for the gcc-11 TSAN build. The backtrace shows a signal handler being called from the event loop of `static_thread_pool`. Needs investigation.

```
281: WARNING: ThreadSanitizer: data race (pid=2040)
281:   Write of size 1 at 0x7ffe43e3c9d9 by main thread:
281:     #0 Catch::RunContext::handleExpr(Catch::AssertionInfo const&, Catch::ITransientExpression const&, Catch::AssertionReaction&) <null> (test.stdexec+0xf78ba)
281:     #1 Catch::AssertionHandler::handleExpr(Catch::ITransientExpression const&) <null> (test.stdexec+0xa97df)
281:     #2 (anonymous namespace)::____C_A_T_C_H____T_E_S_T____28() <null> (test.stdexec+0x2299cd)
281:     #3 Catch::RunContext::invokeActiveTestCase() <null> (test.stdexec+0xadbf2)
281:     #4 Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) <null> (test.stdexec+0xd9dcf)
281:     #5 Catch::RunContext::runTest(Catch::TestCase const&) <null> (test.stdexec+0xf2654)
281:     #6 Catch::Session::runInternal() <null> (test.stdexec+0x10279d)
281:     #7 Catch::Session::run() <null> (test.stdexec+0x102f35)
281:     #8 main <null> (test.stdexec+0x7ddee)
281: 
281:   Previous write of size 1 at 0x7ffe43e3c9d9 by thread T1:
281:     #0 Catch::RunContext::assertionEnded(Catch::AssertionResult const&) <null> (test.stdexec+0xf6b2d)
281:     #1 Catch::RunContext::handleFatalErrorCondition(Catch::StringRef) <null> (test.stdexec+0xf6e25)
281:     #2 Catch::handleSignal(int) <null> (test.stdexec+0xaa58f)
281:     #3 CallUserSignalHandler ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1924 (libtsan.so.0+0x2d883)
281:     #4 _ZZN4exec6_pool_19static_thread_pool_9operationIN7stdexec3_IdINS3_7__schfr11__receiver2INS1_9schedulerENS3_7__sexprIXtlUlvE139_EENS3_12_GLOBAL__N_16__anonEEENS3_8__detail10__receiverINS3_8__shared10__receiverINS8_IXtlUlvE140_EESB_EENS3_5__env9empty_envEEESI_PA1_NS3_8__mucharEE3__tEEEEEE3__tC4ERS1_PNS0_12remote_queueESR_mRKNS_8nodemaskEENUlPNS0_9task_baseEjE_4_FUNES12_j <null> (test.stdexec+0x225635)
281:     #5 std::thread::_State_impl<std::thread::_Invoker<std::tuple<exec::_pool_::static_thread_pool_::static_thread_pool_(unsigned int, exec::bwos_params, exec::numa_policy*)::{lambda()#1}> > >::_M_run() <null> (test.stdexec+0x17029a)
281:     #6 <null> <null> (libstdc++.so.6+0xdc252)
281: 
281:   Location is stack of main thread.
281: 
281:   Location is global '<null>' at 0x000000000000 ([stack]+0x00000001e9d9)
281: 
281:   Thread T1 (tid=2042, running) created by main thread at:
281:     #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
281:     #1 std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) <null> (libstdc++.so.6+0xdc328)
281:     #2 (anonymous namespace)::____C_A_T_C_H____T_E_S_T____28() <null> (test.stdexec+0x228b0e)
281:     #3 Catch::RunContext::invokeActiveTestCase() <null> (test.stdexec+0xadbf2)
281:     #4 Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) <null> (test.stdexec+0xd9dcf)
281:     #5 Catch::RunContext::runTest(Catch::TestCase const&) <null> (test.stdexec+0xf2654)
281:     #6 Catch::Session::runInternal() <null> (test.stdexec+0x10279d)
281:     #7 Catch::Session::run() <null> (test.stdexec+0x102f35)
281:     #8 main <null> (test.stdexec+0x7ddee)
281: 
281: SUMMARY: ThreadSanitizer: data race (/home/coder/stdexec/build/test/test.stdexec+0xf78ba) in Catch::RunContext::handleExpr(Catch::AssertionInfo const&, Catch::ITransientExpression const&, Catch::AssertionReaction&)
```

### PR DESCRIPTION
**Pull request by ccotter**
Notifying the `local_state` might cause it to be destructed, whiich means the instrusive list's increment might be accessing uninitialized memory.

Fixes #1354

Test plan: I was able to fairly reliably reproduce the TSAN and MSAN diagnostics by defining `local_state_base`'s destructor to set `__next_=nullptr` and adding a `sleep(25ms)` as the first line in `__notify_waiters`. With the fix, I could run the TSAN and MSAN executables for a few minutes and never saw any errors.

### CODE REVIEW

File: include/stdexec/__detail/__shared.hpp [hunk 1]
```diff
@@ -329,7 +329,14 @@ namespace stdexec {
         }
 
         STDEXEC_ASSERT(__waiters_copy.front() != __get_tombstone());
-        for (__local_state_base* __item: __waiters_copy) {
+        for (auto __itr = __waiters_copy.begin(); __itr != __waiters_copy.end(); ) {
```
Comment (ccotter) [inline include/stdexec/__detail/__shared.hpp:332]: I didn't find this fix all that satisfying (it seems a little too "cute"). Open to suggestions here. I considered changing the intrusive slist to handle this better, since the intrusive nature of the data structure leaves the iterator open to such bugs, but that didn't seem like the right thing to do.

**Comment by ccotter** [comment]
If we find any more bugs with the "split is thread-safe" test, we'll need to consider renaming the test!

**Review by ericniebler — APPROVED** [review]

**Comment by ccotter** [comment]
The CI failure seems unrelated?

```
633/739 Test #633: compare two schedulers obtained from different system_context objects .........................................................   Passed    0.02 sec
test 634
        Start 634: system scheduler can produce a sender

634: Test command: /home/coder/stdexec/build/test/test.stdexec "system scheduler can produce a sender"
634: Working Directory: /home/coder/stdexec/build/test
634: Test timeout computed to be: 60
634: Filters: system scheduler can produce a sender
634: ===============================================================================
634: All tests passed (3 assertions in 1 test case)
634: 
634: pure virtual method called
634: terminate called without an active exception
634/739 Test #634: system scheduler can produce a sender .........................................................................................Subprocess aborted***Exception:   0.30 sec
Filters: system scheduler can produce a sender
===============================================================================
```

**Comment by ericniebler** [comment]
THANK YOU so much for finding an fixing this bug. :tada: 

> The CI failure seems unrelated?

yes, unrelated. it only happens with nvc++. i haven't gotten to the bottom of it.
